name: Remote Deploy

on:
  push:
    branches:
      - feat/deploy

jobs:
  remote-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check workflow status
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo "Previous workflow failed. Skipping remote deploy."
          exit 1

      - name: SSH Remote Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Running remote deploy script..."
            bash /home/ubuntu/deploy.sh